apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: preview-sweeper
    app.kubernetes.io/managed-by: kustomize
  name: manager-role
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create","patch","update"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["create","patch","update"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get","list","delete"]