image:
  repository: ghcr.io/seekin4u/preview-sweeper
  tag: "amd64"
  pullPolicy: Always
  #digest: sha256:6004f85bd764b8b65887fde04b816cd25748a1c95a09b1be206edb7486fa5930

replicaCount: 2
leaderElection:
  enabled: true 

#controller envs
sweepEvery: "5m"
ttl: "10m"

metrics:
  enabled: true
  port: 8443
  secure: true
  monitoringns: "monitoring"

#you cant set it to TRUE without installing CRDs
serviceMonitor:
  enabled: true
  labels:
    release: monitoring
  namespace: monitoring
  prometheusServiceAccount:
    name: monitoring-kube-prometheus-prometheus

rbac:
  create: true

serviceAccount:
  create: true
  name: "sweeper-service-account"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi
nodeSelector: {}
tolerations: []
affinity: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: [ "ALL" ]

hardening:
  disableDefaultSAToken: true
